In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [11]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,15,6]
my_lst3=[10,12,3,14,25]

In [23]:
arr=np.array([my_lst1,my_lst2,my_lst3])

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4, 15,  6],
       [10, 12,  3, 14, 25]])

In [25]:
arr.shape

(3, 5)

In [26]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 3,  4, 15],
       [ 6, 10, 12],
       [ 3, 14, 25]])

In [27]:
arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  2,  3,  4, 15,  6, 10, 12,  3, 14, 25]])

In [28]:
arr.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [15],
       [ 6],
       [10],
       [12],
       [ 3],
       [14],
       [25]])

### Indexing

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [31]:
arr[3]

4

In [32]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,15,6]
my_lst3=[10,12,3,14,25]

In [35]:
arr1=np.array([my_lst1,my_lst2,my_lst3])

In [36]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4, 15,  6],
       [10, 12,  3, 14, 25]])

In [38]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4, 15,  6],
       [10, 12,  3, 14, 25]])

In [39]:
arr1[1:]

array([[ 2,  3,  4, 15,  6],
       [10, 12,  3, 14, 25]])

In [40]:
arr1[:-1,0:2]

array([[1, 2],
       [2, 3]])

In [44]:
arr1[-1,2:]

array([ 3, 14, 25])

In [45]:
arr1[1:,2:4]

array([[ 4, 15],
       [ 3, 14]])

In [46]:
arr1[1,1:4]

array([ 3,  4, 15])

In [48]:
arr2=np.arange(0,9)

In [49]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
arr3=np.arange(0,10,step=2)
arr3

array([0, 2, 4, 6, 8])

In [51]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [54]:
arr4=np.array([1,2,3,4,5,6,7,8,9])

In [55]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## Coping

In [56]:
arr4[3:]=100

In [57]:
arr4

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [58]:
arr4=arr3

In [59]:
arr4

array([0, 2, 4, 6, 8])

In [60]:
arr4[3:]=500

In [61]:
arr4

array([  0,   2,   4, 500, 500])

In [62]:
arr3

array([  0,   2,   4, 500, 500])

- The changes in one array is replacing the other
- so we use copy operation

In [63]:
arr4=arr.copy()

In [64]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr4[3:7]=800

In [66]:
print(arr4)
print(arr)

[  1   2   3 800 800 800 800   8   9]
[1 2 3 4 5 6 7 8 9]


-some conditions for EDA

In [67]:
val=2
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [69]:
arr%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [70]:
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [71]:
arr[arr<2]

array([1])

In [72]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [74]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

- rand selects random num from 0 to 1

In [81]:
np.random.rand(3,4)

array([[0.64320994, 0.67395405, 0.49148211, 0.62658364],
       [0.59308897, 0.2362341 , 0.85056468, 0.65498797],
       [0.48288992, 0.43532404, 0.94186358, 0.04431805]])

- randn for standard normal distribution

In [77]:
np.random.randn(4,4)

array([[-0.10106518,  0.66486374,  0.59672506,  0.25611079],
       [-1.88288157,  0.29391796,  0.49366499,  1.29134033],
       [-0.33496206,  0.88718054, -0.45360949,  1.15359594],
       [ 1.79677086,  0.52831291,  0.24777046, -0.22089229]])

- randomint:selects the intigers with the given range,size

In [79]:
np.random.randint(0,100,8)

array([48, 38, 33,  9, 82, 22,  7, 23])

- random_sample It selectes random float numbers from 0 to 1 for given size

In [80]:
np.random.random_sample((1,5))

array([[0.19354824, 0.79207836, 0.90402574, 0.03998075, 0.46019461]])